#!/usr/bin/env bash

# Setup Script
set -euo pipefail

mapfile -t PKGS < pkgs.txt
mapfile -t FLPKS < flatpaks.txt

my_defaults() {
    printf '\n'
    printf '%s\n' \
        "set -o vi" \
        "alias vi='nvim'" \
        "alias c='clear'" \
        "export OLLAMA_OFFLINE=true" \
        "export MANPAGER='nvim +Man!'"
    }

echo "Starting Setup..."

touch ~/.bashrc
if [[! grep -q "set -o vi" ~/.bashrc ]]; then
    echo "updating bashrc..."
    my_defaults >> ~/.bashrc
fi

echo "installing packages..."
sudo pacman -Syu --needed --noconfirm "${PKGS[@]}"
flatpak install -y "${FLPKS[@]}"

if [[ ! -d ~/yay ]]
    git clone https://aur.archlinux.org/yay.git
    cd ~/yay && makepkg -si
fi

cd ~ && yay awww-bin

cd ~/dotfiles && stow -nv {foot,fuzzel,niri,nvim,waybar}
