#!/usr/bin/env bash

# Setup Script
set -euo pipefail

mapfile -t PKGS < pkgs.txt
mapfile -t FLPKS < flatpaks.txt
mapfile -t AUR < pkgs.txt

my_defaults() {
    printf '\n'
    printf '%s\n' \
        "set -o vi" \
        "alias vi='nvim'" \
        "alias c='clear'" \
        "export OLLAMA_OFFLINE=true" \
        "export MANPAGER='nvim +Man!'" \
        >> ~/.bashrc
    }

echo "Starting Setup..."
touch "$HOME/.bashrc"
if ! grep -q "set -o vi" ~/.bashrc; then
    echo "updating bashrc..."
    my_defaults
fi

echo "installing packages..."~
if [[ ! -f "$HOME/.local/setup_done" ]]; then
    sudo pacman -Syu --noconfirm
    sudo pacman -S --needed --noconfirm "${PKGS[@]}"
fi

if [[ ! -d "$HOME/yay" ]]; then
    git clone https://aur.archlinux.org/yay.git  "$HOME/yay"
    cd "$HOME/yay" && makepkg -si --no-confirm
    rm -rf "$HOME/yay"
fi

echo "Installing AUR packages..."
yay -S --needed --noconfirm "${AUR[@]}"

echo "Installing flatpaks..."
flatpak install -y flathub "${FLPKS[@]}"

cd "$HOME/Configs" && stow foot fuzzel niri nvim waybar

touch "$HOME/.local/setup_done"
echo "Setup complete."
