#!/usr/bin/env bash

# Setup Script
set -euo pipefail

mapfile -t PKGS < pkgs.txt

my_defaults() {
    printf '\n'
    printf '%s\n' \
    "set -o vi" \
    "alias vi='nvim'" \
    "alias c='clear'" \
    "export OLLAMA_OFFLINE=true" \
    "export MANPAGER='nvim +Man!'"
}

echo "Starting Setup..."

touch ~/.bashrc
if [[! grep -q "set -o vi" ~/.bashrc ]]; then
    echo "updating bashrc..."
    my_defaults >> ~/.bashrc
fi

echo "installing packages..."
sudo pacman -S --needed --noconfirm "${PKGS[@]}"
flatpak install -y app.zen_browser.zen com.github.tchx84.Flatseal
